config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users do
      member do
        patch :toggle_status
      end
    end
    resources :favorite_post_comments, only: [:show, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "homes#top"

  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "search" => "searches#search"

  resources :users, only: [:index,:edit, :show, :create, :update]
  resources :favorite_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :favorite_post_comments, only: [:create,:destroy]
    collection do
      get 'category/:category', to: 'favorite_posts#category', as: :category
    end
  end
  resources :schedule_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]
end

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="text-right">
    <% unless user_signed_in? || admin_signed_in? %>
      <%= link_to admin_session_path do %>
        <p>管理者<i class="fa-solid fa-lock"></i></p>
      <% end %>
    <% end %>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<header class="shadow-sm bg-light">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto,row" style="font-size: 15px;">
          <li class="nav-item col text-center">
            <%= link_to 'TOPページ', root_path, class: 'nav-link text-primary' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item col text-center" >
              <%= link_to 'お気に入りスポット投稿！', new_favorite_post_path, class: 'nav-link text-primary' %>
            </li>
            <%# 改行しても結局２行目が文字数オーバーで中途半端な３行になっちゃったからやめた。
            <li class="nav-item col text-center" >
              <%= link_to ('お気に入り<br>スポット投稿！').html_safe, new_favorite_post_path, class: 'nav-link text-primary'
            </li>
            %>
            <li class="nav-item col text-center">
              <%= link_to 'お気に入りスポット一覧', favorite_posts_path, class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to 'スケジュール新規作成！', new_schedule_post_path, class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to 'スケジュール一覧', schedule_posts_path, class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-primary' %>
            </li>
          <% else %>
            <li class="nav-item col text-center">
              <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-primary' %>
            </li>
            <li class="nav-item col text-center">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-primary' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="d-flex justify-content-center">
    <%= render 'layouts/shared/search' %>
  </div>
</header>

app/views/layouts/shared/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <div class="row">
        <div class="col-md-3 mb-2">
          <%= f.text_field :word, placeholder: "検索キーワード", class: "form-control" %>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.select :range, options_for_select([['ユーザー名', 'User'], ['お気に入り投稿', 'FavoritePost']]), { include_blank: '選択してください' }, { class: "form-control" } %>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]), { include_blank: '検索方法を選択' }, { class: "form-control" } %>
        </div>
        <div class="col-md-3 mb-2 d-flex align-items-center">
          <%= f.submit "検索", class: "btn btn-primary w-100" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>