config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users do
      member do
        patch :toggle_status
      end
    end
    resources :favorite_post_comments, only: [:show, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "homes#top"

  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "search" => "searches#search"

  resources :users, only: [:index,:edit, :show, :create, :update]
  resources :favorite_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :favorite_post_comments, only: [:create,:destroy]
    collection do
      get 'category/:category', to: 'favorite_posts#category', as: :category
    end
  end
  resources :schedule_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  has_one_attached :profile_image
  has_many :favorite_posts, dependent: :destroy
  has_many :schedule_posts, dependent: :destroy
  has_many :favorite_post_comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

      #検索方法の分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  # カスタムバリデーション　ステータス退会の場合
  validate :active_for_authentication?

  def active_for_authentication?
    super && !self.status
  end

  def inactive_message
    self.status ? :account_inactive : super
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end

  def toggle_status
    @user = User.find(params[:id])
    @user.update(status: !@user.status)

    if @user.status
      flash[:notice] = "退会処理を実行しました"
    else
      flash[:notice] = "有効にしました"
    end

    redirect_to admin_user_path(@user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @favorite_posts = @user.favorite_posts.order(created_at: :desc).page(params[:page]).per(6)
    @schedule_posts = @user.schedule_posts.order(created_at: :desc).page(params[:page]).per(6)
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    @user.save
    redirect_to users_path
  end

  def update
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path
    end
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報のアップデートが完了しました！"
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @favorite_posts = FavoritePost.looks(params[:search], params[:word])
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="col-md-6">
    <h2>プロフィール編集</h2>
    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <div class="form-group">
        <%= f.label :name, "ユーザー名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :profile_image, "プロフィール画像" %>
        <div class="mb-3" style="text-align: center;">
          <%= image_tag @user.get_profile_image(150, 150), class: "img-thumbnail" %>
        </div>
        <%= f.file_field :profile_image, class: "form-control-file" %>
      </div>

      <div class="form-group">
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-2">
      <h3><%= @user.name %></h3>
      <div style="text-align: center;">
        <%= image_tag @user.get_profile_image(200, 200) %>
      </div>
      <% if current_user == @user && !current_user.guest_user? %>
        <div class="">
          <%= link_to raw('<i class="fa-solid fa-user-gear"></i> プロフィール編集'), edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" %>
        </div>
      <% end %>
    </div>

    <div class="col-10">
      <h4 style="font-weight: bold;"><%= @user.name %>のお気に入りスポット一覧</h4>
      <div class="row">
        <% @favorite_posts.each do |favorite_post| %>
          <div class="col-6">
            <div class="card mb-4">
              <div class="card-body" style="word-wrap: break-word;">
                <%= image_tag favorite_post.get_favorite_post_image(100, 100) %>
                <label class="d-block text-left">スポット名：<strong><%= link_to favorite_post.spot_name, favorite_post_path(favorite_post.id) %></strong></label>
                <label class="d-block text-left">カテゴリ：<strong><%= I18n.t("categories.#{favorite_post.category}") %></strong></label>
                <label class="d-block text-left">本文：<strong><span> <%= favorite_post.body %></span></strong></label>
                <label class="d-block text-left">投稿ユーザー：<strong><%= favorite_post.user.name %></strong></label>
                <p><%= link_to "#{favorite_post.favorite_post_comments.count} コメント", favorite_post_path(favorite_post.id) %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-12 text-center">
          <nav aria-label="Page navigation example">
            <ul class="pagination pagination-lg justify-content-center" style="font-size: 24px;">
              <%= paginate @favorite_posts, left: 1,right:2 %>
            </ul>
          </nav>
        </div>
      </div>



      <h4 style="font-weight: bold;"><%= @user.name %>のスケジュール一覧</h4>
      <div class="row">
        <% @schedule_posts.each do |schedule_post| %>
          <div class="col-6">
            <div class="card mb-4">
              <div class="card-body">
                <%= image_tag schedule_post.get_schedule_post_image(100, 100) %>
                <p>旅のタイトル：<strong><%= link_to schedule_post.trip_title, schedule_post_path(schedule_post.id) %></strong></p>
                <% if false %>
                  <p>緯度：<strong><%= schedule_post.latitude %></strong></p>
                  <p>経度：<strong><%= schedule_post.longitude %></strong></p>
                <% end %>
                <p>持ち物リスト：<strong><span> <%= schedule_post.inventory_list %></span></strong></p>
                <p>ユーザーネーム：<strong><%= schedule_post.user.name %></strong></p>
                
                <% schedule_post.trip_itineraries.each do |itinerary| %>
                  <div class="card mb-3">
                    <div class="card-body">
                      <p>訪問先名：<%= itinerary.spot_name %></p>
                      <p>日時：<%= itinerary.date_time %></p>
                      <p>メモ：<%= itinerary.body %></p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-12 text-center">
          <nav aria-label="Page navigation example">
            <ul class="pagination pagination-lg justify-content-center" style="font-size: 20px;">
              <%= paginate @schedule_posts, window: 2 %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>