config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users do
      member do
        patch :toggle_status
      end
    end
    resources :favorite_post_comments, only: [:show, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "homes#top"

  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "search" => "searches#search"

  resources :users, only: [:index,:edit, :show, :create, :update]
  resources :favorite_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :favorite_post_comments, only: [:create,:destroy]
    collection do
      get 'category/:category', to: 'favorite_posts#category', as: :category
    end
  end
  resources :schedule_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :user

  has_one_attached :favorite_post_image
  has_many :favorite_post_comments, dependent: :destroy

  enum category: { food: 0, sightseeing: 1, facility: 2, nature: 3, others: 4 }

  def get_favorite_post_image(width, height)
    unless favorite_post_image.attached?
      file_path = Rails.root.join('app/assets/images/post_no_image.jpg')
      favorite_post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    favorite_post_image.variant(resize_to_limit: [width, height]).processed
  end

# 検索方法の分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @favorite_post = FavoritePost.where("spot_name LIKE?","#{word}")
    elsif search == "forward_match"
      @favorite_post = FavoritePost.where("spot_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @favorite_post = FavoritePost.where("spot_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @favorite_post = FavoritePost.where("spot_name LIKE?","%#{word}%")
    else
      @favorite_post = FavoritePost.all
    end
  end

end

app/controllers/favorite_posts_controller.rb
class FavoritePostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @favorite_post = FavoritePost.new
  end

  def create
    @favorite_post = FavoritePost.new(favorite_post_params)
    @favorite_post.user_id = current_user.id
    if @favorite_post.save
      redirect_to favorite_post_path(@favorite_post.id)
    else
      render :new
    end
  end

  def index
    @favorite_posts = FavoritePost.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @favorite_post = FavoritePost.find(params[:id])
    @favorite_post_comment = FavoritePostComment.new
    @favorite_post_comments = @favorite_post.favorite_post_comments.active
  end

  def edit
    @favorite_post = FavoritePost.find(params[:id])
  end

  def update
    @favorite_post = FavoritePost.find(params[:id])
    if @favorite_post.update(favorite_post_params)
      flash[:notice] = "お気に入りスポットの編集が完了しました！"
      redirect_to favorite_post_path(@favorite_post.id)
    else
      render :edit
    end
  end

  def destroy
    @favorite_post = FavoritePost.find(params[:id])
    if @favorite_post.destroy
      flash[:notice] = "お気に入りスポット投稿を削除しました。"
      redirect_to favorite_posts_path
    end
  end

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @favorite_posts = FavoritePost.looks(params[:search], params[:word])
    end
  end

  def category
    @category = params[:category]
    @favorite_posts = FavoritePost.where(category: @category).page(params[:page]).per(10)
  end

  private

  def favorite_post_params
    params.require(:favorite_post).permit(:spot_name, :category, :body, :favorite_post_image)
  end

  def correct_user
    @favorite_post = current_user.favorite_posts.find_by(id: params[:id])
    redirect_to favorite_post_path(params[:id]) if @favorite_post.nil?
  end
end

app/helpers/favorite_posts_helper.rb
module FavoritePostsHelper
end

app/views/favorite_posts/category.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h1><%= I18n.t("categories.#{@category}") %>カテゴリの一覧</h1>

      <div class="mb-4">
        <% I18n.t('categories').each do |key, value| %>
          <%= link_to value, category_favorite_posts_path(category: key), class: "btn btn-primary m-2" %>
        <% end %>
      </div>

      <% @favorite_posts.each do |favorite_post| %>
        <div class="card mb-4">
          <div class="row no-gutters d-flex align-items-center">
            <div class="col-md-4">
              <%= image_tag favorite_post.get_favorite_post_image(100, 100), class: "card-img mb-3" %>
            </div>
            <div class="col-md-8">
              <div class="card-body" style="word-wrap: break-word;">
                <label class="d-block text-left">スポット名：<strong><%= link_to favorite_post.spot_name, favorite_post_path(favorite_post.id) %></strong></label>
                <label class="d-block text-left">カテゴリ：<strong><%= I18n.t("categories.#{favorite_post.category}") %></strong></label>
                <label class="d-block text-left">本文：<strong><span> <%= favorite_post.body %></span></strong></label>
                <label class="d-block text-left">投稿ユーザー：<strong><%= favorite_post.user.name %></strong></label>
                <label class="d-block text-left"><%= link_to "#{favorite_post.favorite_post_comments.count} コメント", favorite_post_path(favorite_post.id) %></label>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <nav aria-label="Page navigation example">
        <ul class="pagination pagination-lg justify-content-center">
          <%= paginate @favorite_posts, class: 'page-item me-5' %>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/favorite_posts/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>お気に入りスポット編集</h1>
  </div>

  <% if @favorite_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_post.errors.count, "error") %> prohibited this favorite post from being saved:</h2>
      <ul>
        <% @favorite_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @favorite_post do |f| %>
        <div class="form-group">
          <%= f.label :spot_name, "スポット名", for: "inputSpotName" %>
          <%= f.text_field :spot_name, autofocus: true, id:"inputSpotName", placeholder:"スポット名", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category, "カテゴリ", for: "inputCategory" %>
          <%= f.select :category, options_for_select([['飲食', 'food'], ['観光名所', 'sightseeing'], ['施設', 'facility'], ['自然', 'nature'], ['その他', 'others']], @favorite_post.category), { include_blank: '選択してください' }, { class: "form-control" } %>
        </div>
        <div class="form-group">
          <%= f.label :body, "本文", for: "inputBody" %>
          <%= f.text_area :body, autofocus: true, id:"inputBody", placeholder:"本文", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :favorite_post_image, "画像", for: "inputFavoritePostImage" %>
          <%= f.file_field :favorite_post_image, placeholder: "画像", accept: "image/*", class: "form-control-file" %>
        </div>
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/favorite_posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h1>スポット投稿一覧</h1>

      <% @favorite_posts.each do |favorite_post| %>
        <div class="card mb-4">
          <div class="row no-gutters d-flex align-items-center">
            <div class="col-md-4">
              <%= image_tag favorite_post.get_favorite_post_image(100, 100), class: "card-img mb-3" %>
            </div>
            <div class="col-md-8">
              <div class="card-body" style="word-wrap: break-word;">
                <label class="d-block text-left">スポット名：<strong><%= link_to favorite_post.spot_name, favorite_post_path(favorite_post.id) %></strong></label>
                <label class="d-block text-left">カテゴリ：<strong><%= favorite_post.category %></strong></label>
                <label class="d-block text-left">本文：<strong><span> <%= favorite_post.body %></span></strong></label>
                <label class="d-block text-left">投稿ユーザー：<strong><%= favorite_post.user.name %></strong></label>
                <label class="d-block text-left"><%= link_to "#{favorite_post.favorite_post_comments.count} コメント", favorite_post_path(favorite_post.id) %></label>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <nav aria-label="Page navigation example">
        <ul class="pagination pagination-lg justify-content-center">
          <%= paginate @favorite_posts, class: 'page-item me-5' %>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/favorite_posts/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>お気に入りスポットを投稿！</h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @favorite_post do |f| %>
        <div class="form-group">
          <%= f.label :spot_name, "スポット名" %>
          <%= f.text_field :spot_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category, "カテゴリ" %>
          <%= f.select :category, FavoritePost.categories.map { |key, value| [I18n.t("categories.#{key}"), key] }, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "本文" %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :favorite_post_image, "画像" %>
          <%= f.file_field :favorite_post_image, accept: "image/*", class: "form-control-file" %>
        </div>
        <%= f.submit '投稿', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/favorite_posts/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="col-6">
      <h1 class="text-center mb-3">お気に入りスポット詳細</h1>
      <div class="card mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-4">
              <%= image_tag @favorite_post.get_favorite_post_image(150, 150), class: "mb-3" %>
            </div>
            <div class="col-8 d-flex flex-column align-items-normal">
              <label class="ml-3">スポット名：<%= @favorite_post.spot_name %></label>
              <label class="ml-3">カテゴリ：<%= I18n.t("categories.#{@favorite_post.category}") %></label>
              <label class="ml-3">本文：<%= @favorite_post.body %></label>
              <label class="ml-3">ユーザーネーム：<%= link_to @favorite_post.user.name, user_path(@favorite_post.user) %></label>
              <% if current_user == @favorite_post.user %>
                <%= link_to "編集", edit_favorite_post_path(@favorite_post.id), class: "btn btn-primary mt-2" %>
                <%= link_to "削除", favorite_post_path(@favorite_post), method: :delete, class: "btn btn-danger mt-2" %>
              <% end %>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <label class="ml-3">コメント件数：<%= @favorite_post.favorite_post_comments.active.count %></label>
              <% @favorite_post_comments.each do |favorite_post_comment| %>
                <div class="card mt-2">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-4">
                        <%= image_tag favorite_post_comment.user.get_profile_image(200,200), class: "mb-3" %>
                      </div>
                      <div class="col-8 d-flex flex-column align-items-start">
                        <div class="card w-100">
                          <div class="card-body text-wrap">
                            <label class="ml-3 mb-5"><%= favorite_post_comment.favorite_post_comment_body %></label>
                          </div>
                        </div>
                        <label class="ml-3">ユーザーネーム：<%= favorite_post_comment.user.name %></label>
                        <label class="ml-3"><%= favorite_post_comment.created_at.strftime('%Y/%m/%d %H:%M') %></label>
                        <% if favorite_post_comment.user == current_user %>
                          <%= link_to "削除", favorite_post_favorite_post_comment_path(favorite_post_comment.favorite_post, favorite_post_comment), method: :delete, class: "btn btn-danger mt-2" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div>
            <%= form_with model: [@favorite_post, @favorite_post_comment] do |f| %>
              <%= f.text_area :favorite_post_comment_body, rows: '5', placeholder: "コメントをここに", class: "w-100" %>
              <%= f.submit "送信する", class: "btn btn-primary mt-2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>