config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users do
      member do
        patch :toggle_status
      end
    end
    resources :favorite_post_comments, only: [:show, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "homes#top"

  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "search" => "searches#search"

  resources :users, only: [:index,:edit, :show, :create, :update]
  resources :favorite_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :favorite_post_comments, only: [:create,:destroy]
    collection do
      get 'category/:category', to: 'favorite_posts#category', as: :category
    end
  end
  resources :schedule_posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @users = User.all
    @favorite_post_comments = FavoritePostComment.all
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container">
  <h1 class="text-center">ダッシュボード</h1>
  <div class="row">
    <!-- ユーザー一覧 -->
    <div class="col-md-8">
      <h2 class="text-center">全ユーザー一覧</h2>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>ユーザーID</th>
              <th>ユーザー名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to user.name, admin_user_path(user.id) %></td>
                <td><%= user.email %></td>
                <td><%= user.status ? '退会' : '有効' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <!-- コメント一覧 -->
    <div class="col-md-4">
      <h2 class="text-center">コメント一覧</h2>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>ID</th>
              <th>内容</th>
              <th>ユーザー名</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @favorite_post_comments.each do |comment| %>
              <tr>
                <td><%= comment.id %></td>
                <td><%= link_to comment.favorite_post_comment_body, admin_favorite_post_comment_path(comment) %></td>
                <td><%= comment.user.name %></td>
                <td><%= comment.status ? '有効' : '無効' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>